package com.longxing.database.datamodel;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.longxing.database.datamodel.FileInforModel;
import com.longxing.database.datamodel.MediaFileModel;
import com.longxing.database.datamodel.ProfileModel;

import com.longxing.database.datamodel.FileInforModelDao;
import com.longxing.database.datamodel.MediaFileModelDao;
import com.longxing.database.datamodel.ProfileModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fileInforModelDaoConfig;
    private final DaoConfig mediaFileModelDaoConfig;
    private final DaoConfig profileModelDaoConfig;

    private final FileInforModelDao fileInforModelDao;
    private final MediaFileModelDao mediaFileModelDao;
    private final ProfileModelDao profileModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fileInforModelDaoConfig = daoConfigMap.get(FileInforModelDao.class).clone();
        fileInforModelDaoConfig.initIdentityScope(type);

        mediaFileModelDaoConfig = daoConfigMap.get(MediaFileModelDao.class).clone();
        mediaFileModelDaoConfig.initIdentityScope(type);

        profileModelDaoConfig = daoConfigMap.get(ProfileModelDao.class).clone();
        profileModelDaoConfig.initIdentityScope(type);

        fileInforModelDao = new FileInforModelDao(fileInforModelDaoConfig, this);
        mediaFileModelDao = new MediaFileModelDao(mediaFileModelDaoConfig, this);
        profileModelDao = new ProfileModelDao(profileModelDaoConfig, this);

        registerDao(FileInforModel.class, fileInforModelDao);
        registerDao(MediaFileModel.class, mediaFileModelDao);
        registerDao(ProfileModel.class, profileModelDao);
    }
    
    public void clear() {
        fileInforModelDaoConfig.clearIdentityScope();
        mediaFileModelDaoConfig.clearIdentityScope();
        profileModelDaoConfig.clearIdentityScope();
    }

    public FileInforModelDao getFileInforModelDao() {
        return fileInforModelDao;
    }

    public MediaFileModelDao getMediaFileModelDao() {
        return mediaFileModelDao;
    }

    public ProfileModelDao getProfileModelDao() {
        return profileModelDao;
    }

}
